apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tiny-llm"
  namespace: tenant-b
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=tiny-llm
        - --model_id=arnir0/Tiny-LLM
        - --backend=huggingface