apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "pytorch-resnet"
  namespace: tenant-c
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    pytorch:
      storageUri: "gs://kfserving-examples/models/torchserve/image_classifier/v1"