apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: tenant-a
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
