apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tensorflow-mnist"
  namespace: tenant-b
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    tensorflow:
      storageUri: "gs://kfserving-examples/models/tensorflow/mnist"
