apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-inference-gateway
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ai-inference-gateway
  schema:
    name: OpenAI
  llmRequestCosts:
  - metadataKey: llm_input_token
    type: InputToken
  - metadataKey: llm_output_token
    type: OutputToken
  - metadataKey: llm_total_token
    type: TotalToken
  rules:
  - matches:
    - headers:
      - type: Exact
        name: "x-tenant"
        value: "tenant-a"
      - type: Exact
        name: "x-ai-eg-model"
        value: "sklearn-iris"
    backendRefs:
    - name: sklearn-iris-backend
      weight: 1
  - matches:
    - headers:
      - type: Exact
        name: "x-tenant"
        value: "tenant-c"
      - type: Exact
        name: "x-ai-eg-model"
        value: "pytorch-resnet"
    backendRefs:
    - name: pytorch-resnet-backend
      weight: 1
  - matches:
    - {}
    backendRefs:
    - name: istio-gateway-backend
      weight: 1