apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tensorflow-mnist-split
  namespace: tenant-b
  labels:
    serving.kserve.io/inferenceservice: tensorflow-mnist
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/inference-gateway
  http:
  - match:
    - uri:
        prefix: "/v2/models/tensorflow-mnist"
    route:
    - destination:
        host: tensorflow-mnist-v2-predictor-default.tenant-b.svc.cluster.local
        port:
          number: 80
      weight: 100
