apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: sklearn-iris-backend
  namespace: envoy-gateway-system
spec:
  fqdn: sklearn-iris-predictor-default.tenant-a.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/v1/models/sklearn-iris"
  timeout: 30s
  retry:
    numRetries: 3
    backoffBaseInterval: 1s
    backoffMaxInterval: 10s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: pytorch-resnet-backend
  namespace: envoy-gateway-system
spec:
  fqdn: pytorch-resnet-predictor-default.tenant-c.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/v1/models/pytorch-resnet"
  timeout: 30s
  retry:
    numRetries: 3
    backoffBaseInterval: 1s
    backoffMaxInterval: 10s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: istio-gateway-backend
  namespace: envoy-gateway-system
spec:
  fqdn: istio-ingressgateway.istio-system.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/"
  timeout: 30s
  retry:
    numRetries: 2
    backoffBaseInterval: 500ms
    backoffMaxInterval: 5s