apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ai-inference-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: ai-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: ai-gateway-tls
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-inference-gateway
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ai-inference-gateway
  schema:
    name: OpenAI
  rules:
  - matches:
    - headers:
      - type: Exact
        name: "x-tenant"
        value: "tenant-a"
      - type: Exact
        name: "x-ai-eg-model"
        value: "sklearn-iris"
    backendRefs:
    - name: sklearn-iris-backend
      weight: 1
  - matches:
    - headers:
      - type: Exact
        name: "x-tenant"
        value: "tenant-c"
      - type: Exact
        name: "x-ai-eg-model"
        value: "pytorch-resnet"
    backendRefs:
    - name: pytorch-resnet-backend
      weight: 1
  - matches:
    - {}
    backendRefs:
    - name: istio-gateway-backend
      weight: 1