apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ai-gateway-traffic-policy
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ai-inference-gateway
  rateLimit:
    type: Global
    global:
      rules:
      # Per-tenant rate limiting
      - clientSelectors:
        - headers:
          - name: "x-tenant"
            value: "tenant-a"
        limit:
          requests: 100
          unit: Minute
      - clientSelectors:
        - headers:
          - name: "x-tenant"
            value: "tenant-b"
        limit:
          requests: 100
          unit: Minute
      - clientSelectors:
        - headers:
          - name: "x-tenant"
            value: "tenant-c"
        limit:
          requests: 100
          unit: Minute
      # Global rate limiting
      - limit:
          requests: 1000
          unit: Minute
  circuitBreaker:
    maxConnections: 100
    maxPendingRequests: 50
    maxParallelRequests: 200
    maxParallelRetries: 10
  retry:
    numRetries: 3
    retryOn:
      httpStatusCodes:
      - 500
      - 502
      - 503
      - 504
      triggers:
      - "connect-failure"
      - "refused-stream"
  timeout:
    tcp:
      connectTimeout: 10s
    http:
      requestTimeout: 30s
      connectionIdleTimeout: 60s
  healthCheck:
    active:
      timeout: 1s
      interval: 3s
      unhealthyThreshold: 3
      healthyThreshold: 2
      type: HTTP
      http:
        path: "/health"
        method: GET
        expectedStatuses:
        - 200
        - 201