apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sklearn-iris
  namespace: tenant-a
  labels:
    serving.kserve.io/inferenceservice: sklearn-iris
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/inference-gateway
  http:
  - match:
    - uri:
        prefix: "/v2/models/sklearn-iris"
    route:
    - destination:
        host: sklearn-iris-predictor-default.tenant-a.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tensorflow-mnist
  namespace: tenant-b
  labels:
    serving.kserve.io/inferenceservice: tensorflow-mnist
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/inference-gateway
  http:
  - match:
    - uri:
        prefix: "/v2/models/tensorflow-mnist"
    route:
    - destination:
        host: tensorflow-mnist-predictor-default.tenant-b.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pytorch-resnet
  namespace: tenant-c
  labels:
    serving.kserve.io/inferenceservice: pytorch-resnet
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/inference-gateway
  http:
  - match:
    - uri:
        prefix: "/v2/models/pytorch-resnet"
    route:
    - destination:
        host: pytorch-resnet-predictor-default.tenant-c.svc.cluster.local
        port:
          number: 80
