apiVersion: v1
kind: ConfigMap
metadata:
  name: management-server-config
  namespace: default
data:
  server.js: |
    const express = require('express');
    const jwt = require('jsonwebtoken');
    const crypto = require('crypto');
    const { exec } = require('child_process');
    const fs = require('fs').promises;
    const path = require('path');
    const yaml = require('js-yaml');

    const app = express();
    const PORT = process.env.PORT || 8080;

    // Middleware
    app.use(express.json());
    app.use(express.urlencoded({ extended: true }));

    // Serve static files from the React app build directory
    const buildPath = path.join(__dirname, 'ui', 'build');
    app.use(express.static(buildPath));

    // CORS - Allow frontend to access API
    app.use((req, res, next) => {
      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
      res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
      if (req.method === 'OPTIONS') {
        res.sendStatus(200);
      } else {
        next();
      }
    });

    // JWT Authentication middleware
    const authenticateToken = (req, res, next) => {
      const authHeader = req.headers['authorization'];
      const token = authHeader && authHeader.split(' ')[1];

      if (!token) {
        return res.status(401).json({ error: 'Access token required' });
      }

      try {
        const decoded = jwt.decode(token);
        if (!decoded || !decoded.tenant) {
          return res.status(403).json({ error: 'Invalid token' });
        }
        req.user = decoded;
        next();
      } catch (error) {
        return res.status(403).json({ error: 'Invalid token' });
      }
    };

    // Utility functions
    const execCommand = (command) => {
      return new Promise((resolve, reject) => {
        exec(command, (error, stdout, stderr) => {
          if (error) {
            reject({ error: error.message, stderr });
          } else {
            resolve(stdout);
          }
        });
      });
    };

    const generateModelYAML = (modelName, tenant, config) => {
      const modelTemplate = {
        apiVersion: 'serving.kserve.io/v1beta1',
        kind: 'InferenceService',
        metadata: {
          name: modelName,
          namespace: tenant
        },
        spec: {
          predictor: {
            minReplicas: config.minReplicas || 1,
            maxReplicas: config.maxReplicas || 3,
            scaleTarget: config.scaleTarget || 60,
            scaleMetric: config.scaleMetric || 'concurrency',
            [config.framework]: {
              storageUri: config.storageUri
            }
          }
        }
      };

      return yaml.dump(modelTemplate);
    };

    // API Routes
    app.get('/health', (req, res) => {
      res.json({ status: 'healthy', timestamp: new Date().toISOString() });
    });

    app.get('/api/tokens', async (req, res) => {
      try {
        const result = await execCommand('kubectl port-forward -n default svc/jwt-server 8081:8080 > /dev/null 2>&1 & sleep 2 && curl -s http://localhost:8081/tokens && pkill -f "kubectl port-forward.*jwt-server"');
        const tokens = JSON.parse(result);
        res.json(tokens);
      } catch (error) {
        res.status(500).json({ error: 'Failed to retrieve tokens', details: error.message });
      }
    });

    app.get('/api/models', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const command = `kubectl get inferenceservices -n ${tenant} -o json`;
        const result = await execCommand(command);
        const models = JSON.parse(result);
        
        const modelList = models.items.map(model => ({
          name: model.metadata.name,
          namespace: model.metadata.namespace,
          status: model.status?.conditions?.[0]?.status || 'Unknown',
          ready: model.status?.conditions?.[0]?.type === 'Ready' && model.status?.conditions?.[0]?.status === 'True',
          url: model.status?.url,
          predictor: model.spec.predictor,
          createdAt: model.metadata.creationTimestamp
        }));

        res.json({ models: modelList });
      } catch (error) {
        res.status(500).json({ error: 'Failed to list models', details: error.message });
      }
    });

    app.get('/api/models/:modelName', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const modelName = req.params.modelName;
        const command = `kubectl get inferenceservice ${modelName} -n ${tenant} -o json`;
        const result = await execCommand(command);
        const model = JSON.parse(result);
        
        const modelInfo = {
          name: model.metadata.name,
          namespace: model.metadata.namespace,
          status: model.status?.conditions?.[0]?.status || 'Unknown',
          ready: model.status?.conditions?.[0]?.type === 'Ready' && model.status?.conditions?.[0]?.status === 'True',
          url: model.status?.url,
          predictor: model.spec.predictor,
          createdAt: model.metadata.creationTimestamp,
          conditions: model.status?.conditions || []
        };

        res.json(modelInfo);
      } catch (error) {
        if (error.stderr && error.stderr.includes('not found')) {
          res.status(404).json({ error: 'Model not found' });
        } else {
          res.status(500).json({ error: 'Failed to get model', details: error.message });
        }
      }
    });

    app.post('/api/models', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const { name, framework, storageUri, minReplicas, maxReplicas, scaleTarget, scaleMetric } = req.body;

        if (!name || !framework || !storageUri) {
          return res.status(400).json({ error: 'Missing required fields: name, framework, storageUri' });
        }

        const supportedFrameworks = ['sklearn', 'tensorflow', 'pytorch', 'onnx', 'xgboost'];
        if (!supportedFrameworks.includes(framework)) {
          return res.status(400).json({ error: `Unsupported framework. Supported: ${supportedFrameworks.join(', ')}` });
        }

        const config = {
          framework,
          storageUri,
          minReplicas: minReplicas || 1,
          maxReplicas: maxReplicas || 3,
          scaleTarget: scaleTarget || 60,
          scaleMetric: scaleMetric || 'concurrency'
        };

        const modelYAML = generateModelYAML(name, tenant, config);
        const tempFile = `/tmp/model-${name}-${Date.now()}.yaml`;
        
        await fs.writeFile(tempFile, modelYAML);
        
        const command = `kubectl apply -f ${tempFile}`;
        await execCommand(command);
        
        await fs.unlink(tempFile);

        res.status(201).json({ 
          message: 'Model created successfully',
          name,
          namespace: tenant,
          config
        });
      } catch (error) {
        res.status(500).json({ error: 'Failed to create model', details: error.message });
      }
    });

    app.put('/api/models/:modelName', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const modelName = req.params.modelName;
        const { framework, storageUri, minReplicas, maxReplicas, scaleTarget, scaleMetric } = req.body;

        const getCommand = `kubectl get inferenceservice ${modelName} -n ${tenant} -o json`;
        const existingModel = JSON.parse(await execCommand(getCommand));

        const config = {
          framework: framework || Object.keys(existingModel.spec.predictor).find(k => k !== 'minReplicas' && k !== 'maxReplicas' && k !== 'scaleTarget' && k !== 'scaleMetric'),
          storageUri: storageUri || existingModel.spec.predictor[framework]?.storageUri,
          minReplicas: minReplicas || existingModel.spec.predictor.minReplicas,
          maxReplicas: maxReplicas || existingModel.spec.predictor.maxReplicas,
          scaleTarget: scaleTarget || existingModel.spec.predictor.scaleTarget,
          scaleMetric: scaleMetric || existingModel.spec.predictor.scaleMetric
        };

        const modelYAML = generateModelYAML(modelName, tenant, config);
        const tempFile = `/tmp/model-${modelName}-${Date.now()}.yaml`;
        
        await fs.writeFile(tempFile, modelYAML);
        
        const command = `kubectl apply -f ${tempFile}`;
        await execCommand(command);
        
        await fs.unlink(tempFile);

        res.json({ 
          message: 'Model updated successfully',
          name: modelName,
          namespace: tenant,
          config
        });
      } catch (error) {
        if (error.stderr && error.stderr.includes('not found')) {
          res.status(404).json({ error: 'Model not found' });
        } else {
          res.status(500).json({ error: 'Failed to update model', details: error.message });
        }
      }
    });

    app.delete('/api/models/:modelName', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const modelName = req.params.modelName;
        const command = `kubectl delete inferenceservice ${modelName} -n ${tenant}`;
        await execCommand(command);

        res.json({ message: 'Model deleted successfully', name: modelName, namespace: tenant });
      } catch (error) {
        if (error.stderr && error.stderr.includes('not found')) {
          res.status(404).json({ error: 'Model not found' });
        } else {
          res.status(500).json({ error: 'Failed to delete model', details: error.message });
        }
      }
    });

    app.post('/api/models/:modelName/predict', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const modelName = req.params.modelName;
        const inputData = req.body;

        const getCommand = `kubectl get inferenceservice ${modelName} -n ${tenant} -o jsonpath='{.status.url}'`;
        const modelUrl = await execCommand(getCommand);

        if (!modelUrl) {
          return res.status(404).json({ error: 'Model not ready or not found' });
        }

        const curlCommand = `curl -s -X POST ${modelUrl}/v1/models/${modelName}:predict \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${req.headers.authorization.split(' ')[1]}" \
          -d '${JSON.stringify(inputData)}'`;
        
        const result = await execCommand(curlCommand);
        const prediction = JSON.parse(result);

        res.json(prediction);
      } catch (error) {
        res.status(500).json({ error: 'Failed to make prediction', details: error.message });
      }
    });

    app.get('/api/models/:modelName/logs', authenticateToken, async (req, res) => {
      try {
        const tenant = req.user.tenant;
        const modelName = req.params.modelName;
        const lines = req.query.lines || 100;
        
        const command = `kubectl logs -n ${tenant} -l serving.kserve.io/inferenceservice=${modelName} --tail=${lines}`;
        const logs = await execCommand(command);

        res.json({ logs: logs.split('\n') });
      } catch (error) {
        res.status(500).json({ error: 'Failed to get logs', details: error.message });
      }
    });

    app.get('/api/tenant', authenticateToken, (req, res) => {
      res.json({
        tenant: req.user.tenant,
        user: req.user.name || req.user.sub,
        issuer: req.user.iss,
        audience: req.user.aud,
        expiresAt: new Date(req.user.exp * 1000).toISOString()
      });
    });

    app.get('/api/frameworks', (req, res) => {
      res.json({
        frameworks: [
          { name: 'sklearn', description: 'Scikit-learn models' },
          { name: 'tensorflow', description: 'TensorFlow models' },
          { name: 'pytorch', description: 'PyTorch models' },
          { name: 'onnx', description: 'ONNX models' },
          { name: 'xgboost', description: 'XGBoost models' }
        ]
      });
    });

    // Serve React app for all other routes (SPA fallback)
    app.get('*', (req, res) => {
      res.sendFile(path.join(buildPath, 'index.html'));
    });

    app.use((error, req, res, next) => {
      console.error('Error:', error);
      res.status(500).json({ error: 'Internal server error' });
    });

    app.listen(PORT, '0.0.0.0', () => {
      console.log(`Management server running on port ${PORT}`);
      console.log('Available endpoints:');
      console.log('  GET  /health - Health check');
      console.log('  GET  /api/tokens - Get JWT tokens');
      console.log('  GET  /api/models - List models');
      console.log('  GET  /api/models/:name - Get model details');
      console.log('  POST /api/models - Create model');
      console.log('  PUT  /api/models/:name - Update model');
      console.log('  DELETE /api/models/:name - Delete model');
      console.log('  POST /api/models/:name/predict - Make prediction');
      console.log('  GET  /api/models/:name/logs - Get model logs');
      console.log('  GET  /api/tenant - Get tenant info');
      console.log('  GET  /api/frameworks - List supported frameworks');
      console.log('  GET  /* - Serve React application');
    });
  package.json: |
    {
      "name": "inference-management",
      "version": "1.0.0",
      "description": "Consolidated Management API and UI for AI/ML inference platform",
      "main": "server.js",
      "scripts": {
        "start": "node server.js",
        "dev": "nodemon server.js"
      },
      "dependencies": {
        "express": "^4.18.2",
        "jsonwebtoken": "^9.0.2",
        "js-yaml": "^4.1.0"
      },
      "devDependencies": {
        "nodemon": "^3.0.1"
      },
      "keywords": ["kubernetes", "kserve", "ai", "ml", "inference", "management"],
      "author": "Inference-in-a-Box",
      "license": "MIT"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-ui-source
  namespace: default
data:
  package.json: |
    {
      "name": "inference-management-ui",
      "version": "1.0.0",
      "description": "Web UI for AI/ML inference platform management",
      "private": true,
      "dependencies": {
        "@testing-library/jest-dom": "^5.16.4",
        "@testing-library/react": "^13.3.0",
        "@testing-library/user-event": "^13.5.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.3.0",
        "react-scripts": "5.0.1",
        "axios": "^1.4.0",
        "@uiw/react-json-view": "^1.6.8",
        "react-hot-toast": "^2.4.1",
        "lucide-react": "^0.263.1"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": [
          "react-app",
          "react-app/jest"
        ]
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      },
      "homepage": "."
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-ui-build
  namespace: default
data: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: management-service
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: management-service
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: management-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: management-service
subjects:
- kind: ServiceAccount
  name: management-service
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
  namespace: default
  labels:
    app: management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      serviceAccountName: management-service
      initContainers:
      - name: ui-builder
        image: node:18-alpine
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Building React UI..."
          cd /tmp/ui-source
          npm install
          npm run build
          echo "Copying build artifacts..."
          cp -r build/* /tmp/ui-build/
          echo "UI build complete"
        volumeMounts:
        - name: ui-source
          mountPath: /tmp/ui-source
        - name: ui-build
          mountPath: /tmp/ui-build
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      containers:
      - name: management-service
        image: node:18-alpine
        command:
        - /bin/sh
        - -c
        - |
          set -e
          # Install kubectl
          apk add --no-cache curl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
          
          # Setup application
          cd /app
          npm install
          
          # Create UI build directory structure
          mkdir -p ui/build
          cp -r /tmp/ui-build/* ui/build/ 2>/dev/null || echo "No UI build artifacts found"
          
          # Start server
          node server.js
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: server-config
          mountPath: /app
        - name: ui-build
          mountPath: /tmp/ui-build
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: server-config
        configMap:
          name: management-server-config
      - name: ui-source
        configMap:
          name: management-ui-source
      - name: ui-build
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
  namespace: default
  labels:
    app: management-service
spec:
  selector:
    app: management-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP