apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-v2"
  namespace: tenant-a
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 2
    scaleTarget: 60
    scaleMetric: concurrency
    sklearn:
      storageUri: "gs://kfserving-examples/models/sklearn/v1.0/iris"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sklearn-iris-split
  namespace: tenant-a
  labels:
    serving.kserve.io/inferenceservice: sklearn-iris
spec:
  hosts:
  - "sklearn-iris.tenant-a.127.0.0.1.sslip.io"
  gateways:
  - istio-system/inference-gateway
  http:
  - match:
    - uri:
        prefix: "/v1/models/sklearn-iris"
    route:
    - destination:
        host: sklearn-iris-predictor-default.tenant-a.svc.cluster.local
        port:
          number: 80
      weight: 90
    - destination:
        host: sklearn-iris-v2-predictor-default.tenant-a.svc.cluster.local
        port:
          number: 80
      weight: 10