# AI Gateway Service Backends (aigateway.envoyproxy.io/v1alpha1)
# These reference the standard Backend resources and add AI-specific schema
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: sklearn-iris-backend
  namespace: envoy-gateway-system
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: sklearn-iris-backend
  schema:
    name: OpenAI
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: pytorch-resnet-backend
  namespace: envoy-gateway-system
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: pytorch-resnet-backend
  schema:
    name: OpenAI
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: istio-gateway-backend
  namespace: envoy-gateway-system
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: istio-gateway-backend
  schema:
    name: OpenAI

---
# Legacy AI Service Backends (gateway.envoyproxy.io/v1alpha1)
# These are standalone AI backends with direct service configuration
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: sklearn-iris-direct-backend
  namespace: envoy-gateway-system
spec:
  fqdn: sklearn-iris-predictor-default.tenant-a.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/v1/models/sklearn-iris"
  timeout: 60s
  retry:
    numRetries: 3
    backoffBaseInterval: 1s
    backoffMaxInterval: 10s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: pytorch-resnet-direct-backend
  namespace: envoy-gateway-system
spec:
  fqdn: pytorch-resnet-predictor-default.tenant-c.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/v1/models/pytorch-resnet"
  timeout: 60s
  retry:
    numRetries: 3
    backoffBaseInterval: 1s
    backoffMaxInterval: 10s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: istio-gateway-direct-backend
  namespace: envoy-gateway-system
spec:
  fqdn: istio-ingressgateway.istio-system.svc.cluster.local
  port: 80
  protocol: HTTP
  path:
    prefix: "/"
  timeout: 30s
  retry:
    numRetries: 2
    backoffBaseInterval: 500ms
    backoffMaxInterval: 5s