apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-ui
  namespace: default
  labels:
    app: management-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-ui
  template:
    metadata:
      labels:
        app: management-ui
    spec:
      containers:
      - name: management-ui
        image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/management-ui:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: management-ui
  namespace: default
  labels:
    app: management-ui
spec:
  selector:
    app: management-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP