apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "pytorch-resnet"
  namespace: tenant-c
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    pytorch:
      storageUri: "gs://kserve-examples/models/pytorch/resnet"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
