apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tensorflow-mnist"
  namespace: tenant-b
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    tensorflow:
      storageUri: "https://raw.githubusercontent.com/tduffy000/kfserving-uri-examples/master/tensorflow/frozen/model_artifacts.tar.gz"
