apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tensorflow-mnist"
  namespace: tenant-b
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 3
    scaleTarget: 60
    scaleMetric: concurrency
    tensorflow:
      storageUri: "https://storage.googleapis.com/tfserving-mnist-demo/mnist-tf-2.0.0.tar.gz"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
