name: PR Validation

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quick-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install prerequisites
      run: |
        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
        # Install kind
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/
        
        # Install helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        
        # Install jq
        sudo apt-get update && sudo apt-get install -y jq
        
    - name: Validate syntax
      run: |
        echo "🔍 Validating YAML and shell script syntax..."
        
        # Validate YAML files
        find . -name "*.yaml" -o -name "*.yml" | while read file; do
          echo "Checking $file..."
          python3 -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
        done
        
        # Validate shell scripts
        find . -name "*.sh" | while read file; do
          echo "Checking $file..."
          bash -n "$file" || exit 1
        done
        
        echo "✅ All syntax checks passed"
        
    - name: Test cluster creation
      run: |
        echo "🧪 Testing Kind cluster creation..."
        chmod +x scripts/clusters/create-kind-cluster.sh
        ./scripts/clusters/create-kind-cluster.sh
        
        # Verify cluster
        kubectl cluster-info
        kubectl get nodes
        
        echo "✅ Kind cluster creation successful"
        
    - name: Validate Kubernetes manifests
      run: |
        echo "🔍 Validating Kubernetes manifests..."
        
        # Install CRDs for validation
        helm upgrade --install envoy-gateway oci://docker.io/envoyproxy/gateway-helm \
          --version 1.4.1 \
          --namespace envoy-gateway-system \
          --create-namespace
          
        helm upgrade -i aieg-crd oci://docker.io/envoyproxy/ai-gateway-crds-helm \
          --version v0.2.1 \
          --namespace envoy-ai-gateway-system \
          --create-namespace
          
        # Wait for CRDs
        kubectl wait --timeout=60s --for=condition=Available -n envoy-gateway-system deployment/envoy-gateway
        
        # Dry-run validation
        kubectl apply --dry-run=client -f configs/envoy-gateway/ --recursive
        
        echo "✅ All manifests validated"
        
    - name: Cleanup
      if: always()
      run: |
        kind delete clusters --all || true