apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tenant-a-isolation
  namespace: tenant-a
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET", "POST"]
    when:
    - key: request.headers[x-jwt-tenant]
      values: ["tenant-a"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tenant-b-isolation
  namespace: tenant-b
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET", "POST"]
    when:
    - key: request.headers[x-jwt-tenant]
      values: ["tenant-b"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tenant-c-isolation
  namespace: tenant-c
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET", "POST"]
    when:
    - key: request.headers[x-jwt-tenant]
      values: ["tenant-c"]